    SELECT DISTINCT "FC"."FIC_ID", "FC"."PRF_CODIGO","PF"."LTC_ID","CP"."CMP_ID","C"."CMP_NOMBRE"
    FROM "INTEGRACION"."COMPETENCIAXPROGRAMA" AS "CP"
    INNER JOIN "INTEGRACION"."COMPETENCIA" AS "C" ON "CP"."CMP_ID" = "C"."CMP_ID"
    INNER JOIN "INTEGRACION"."V_PROGRAMA_FORMACION_B" AS "PF" ON "C"."LTC_ID" = "PF"."LTC_ID"
    INNER JOIN "INTEGRACION"."V_FICHA_CARACTERIZACION_B" AS "FC" ON "PF"."PRF_CODIGO" = "FC"."PRF_CODIGO"
    WHERE "FC"."FIC_ID" = 2966656 ORDER BY "CP"."CMP_ID" ASC

    select c2.* from "INTEGRACION"."V_FICHA_CARACTERIZACION_B" fic 
    inner join "INTEGRACION"."V_PROGRAMA_FORMACION_B" prf on fic."PRF_ID" = prf."PRF_ID" 
    inner join "INTEGRACION"."COMPETENCIAXPROGRAMA" c on c."PRF_ID" = prf."PRF_ID" 
    inner join "INTEGRACION"."COMPETENCIA" c2 on c2."CMP_ID" = c."CMP_ID" 
    where fic."FIC_ID" = 2141007;

    select c2.* from "INTEGRACION"."V_PROGRAMA_FORMACION_B" prf 
    inner join "INTEGRACION"."COMPETENCIAXPROGRAMA" c on c."PRF_ID" = prf."PRF_ID" 
    inner join "INTEGRACION"."COMPETENCIA" c2 on c2."CMP_ID" = c."CMP_ID" 
    where prf."PRF_ID" = 60516;

    SELECT DISTINCT "FC"."FIC_ID", "FC"."PRF_CODIGO","PF"."LTC_ID","CP"."CMP_ID","C"."CMP_NOMBRE"
    FROM "INTEGRACION"."COMPETENCIAXPROGRAMA" AS "CP"
    INNER JOIN "INTEGRACION"."COMPETENCIA" AS "C" ON "CP"."CMP_ID" = "C"."CMP_ID"
    INNER JOIN "INTEGRACION"."V_PROGRAMA_FORMACION_B" AS "PF" ON "C"."LTC_ID" = "PF"."LTC_ID"
    INNER JOIN "INTEGRACION"."V_FICHA_CARACTERIZACION_B" AS "FC" ON "PF"."PRF_CODIGO" = "FC"."PRF_CODIGO"
    WHERE "FC"."FIC_ID" = $curso ORDER BY "CP"."CMP_ID" ASC

    SELECT "P"."LMS_ID", "P"."NUM_DOC_IDENTIDAD", "P"."PER_NOMBRE","P"."PER_PRIMER_APELLIDO","P"."PER_SEGUNDO_APELLIDO", "ADR"."CMP_ID", "R"."REA_NOMBRE","ADR"."REA_ID", 
    "ADR"."ADR_EVALUACION_COMPETENCIA","ADR"."ADR_EVALUACION_RESULTADO" 
    FROM "INTEGRACION"."V_PERSONA_B" AS "P"
    JOIN "INTEGRACION"."V_REGISTRO_ACADEMICO_B" AS "RA" ON "P"."NIS" = "RA"."NIS"
    JOIN "INTEGRACION"."V_APRENDIZXDETALLE_RUTA_B" AS "ADR" ON "RA"."RGA_ID" = "ADR"."RGA_ID" 
    JOIN "INTEGRACION"."RESULTADO_APRENDIZAJE" AS "R" ON "ADR"."REA_ID" = "R"."REA_ID" 

    create view "INTEGRACION".vista_competencias2 as select c2.*, fic."FIC_ID" 
    from "INTEGRACION"."V_FICHA_CARACTERIZACION_B" fic 
    inner join "INTEGRACION"."V_PROGRAMA_FORMACION_B" prf on fic."PRF_ID" = prf."PRF_ID" 
    inner join "INTEGRACION"."COMPETENCIAXPROGRAMA" c on c."PRF_ID" = prf."PRF_ID" 
    inner join "INTEGRACION"."COMPETENCIA" c2 on c2."CMP_ID" = c."CMP_ID" 

    select * from "INTEGRACION".vista_competencias2
    where "FIC_ID" = 2966656 and "CMP_ACTIVO" = '1';

    create view "INTEGRACION".vista_optimizada3 as select distinct "P"."LMS_ID", "P"."NUM_DOC_IDENTIDAD", "P"."PER_NOMBRE","P"."PER_PRIMER_APELLIDO","P"."PER_SEGUNDO_APELLIDO", "ADR"."CMP_ID", "R"."REA_NOMBRE","ADR"."REA_ID", 
    "ADR"."ADR_EVALUACION_COMPETENCIA","ADR"."ADR_EVALUACION_RESULTADO" 
    FROM "INTEGRACION"."V_PERSONA_B" AS "P"
    JOIN "INTEGRACION"."V_REGISTRO_ACADEMICO_B" AS "RA" ON "P"."NIS" = "RA"."NIS"
    join "INTEGRACION"."V_FICHA_CARACTERIZACION_B" as "FC" on "RA"."FIC_ID" = "FC"."FIC_ID"
    join "INTEGRACION"."V_PROGRAMA_FORMACION_B" as "PRF" on "FC"."PRF_ID" = "PRF"."PRF_ID" 
    join "INTEGRACION"."COMPETENCIA" as "C" on "PRF"."LTC_ID" = "C"."LTC_ID" 
    join "INTEGRACION"."COMPETENCIAXPROGRAMA" as "C2" on "C"."CMP_ID" ="C2"."CMP_ID"  
    JOIN "INTEGRACION"."RESULTADO_APRENDIZAJE" AS "R" ON "C2"."CPR_ID" = "R"."CPR_ID" 
    JOIN "INTEGRACION"."V_APRENDIZXDETALLE_RUTA_B" AS "ADR" ON "R"."REA_ID" = "ADR"."REA_ID" 
    WHERE "C"."CMP_ID" = 37714 AND "ADR"."REA_ID" = 665124 AND "FC"."FIC_ID" = 2966656;



